arch:
  - ppc64le
  - amd64
sudo: false

language: erlang

before_install:
  - pip install --user cpp-coveralls coveralls-merge
  - if [ "$TRAVIS_ARCH" = "ppc64le" ]; then sudo apt-get update; sudo apt-get install rebar; fi

install:
  - rebar get-deps

script: rebar compile xref && rebar skip_deps=true eunit

otp_release:
  - 18.0
  - 18.3
  - 19.3
  - 20.3
  - 21.3
  - 22.3

# Disable otp_release 18.3 & 19.3 as these releases are not supported on Ubuntu16.04 for arch: ppc64le
jobs: 
 exclude:
  - arch: ppc64le
    otp_release: 18.3
  - arch: ppc64le
    otp_release: 19.3
  
after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
